---
# https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
    - package-ecosystem: github-actions
      directory: /
      schedule:
          interval: weekly
      commit-message:
          prefix: chore
          include: scope
    - package-ecosystem: pip
      directory: /jarvis_proto_sdk
      schedule:
        interval: weekly
      target-branch: master
      open-pull-requests-limit: 10
      commit-message:
        prefix: chore
        include: scope
