coverage:
  status:
    project:
      default:
        target: 75%

ignore:
  - "setup.py"
  - "version.py"
  - "jarvis_sdk/example.py"
  - "jarvis_sdk/indykite"
  - "jarvis_sdk/validate"
  - "tests/fixtures"
  - "tests/helpers"
