coverage:
  status:
    project:
      default:
        target: 75%
        threshold: 1%

ignore:
  - "setup.py"
  - "version.py"
  - "jarvis_sdk/api.py"
  - "jarvis_sdk/example.py"
  - "jarvis_sdk/indykite"
  - "jarvis_sdk/validate"
  - "jarvis_sdk/cmd/helper.py"
  - "tests"
