coverage:
  status:
    project:
      default:
        target: 75%
        threshold: 3%
    patch:
        default:
            target: 75%
            threshold: 10%


ignore:
  - "setup.py"
  - "version.py"
  - "indykite_sdk/api.py"
  - "indykite_sdk/api_helper.py"
  - "indykite_sdk/example.py"
  - "indykite_sdk/indykite"
  - "indykite_sdk/validate"
  - "indykite_sdk/identity/helper.py"
  - "indykite_sdk/config/helper.py"
  - "indykite_sdk/config/get_schema.py"
  - "indykite_sdk/model/unique_name_identifier.py"
  - "indykite_sdk/model/email_attachment.py"
  - "indykite_sdk/model/import_digital_twin.py"
  - "indykite_sdk/model/get_schema.py"
  - "indykite_sdk/utils"
  - "tests"
  - "examples"
  - "prepare_docs"
