---
coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 3%
    patch:
      default:
        target: 85%
        threshold: 10%

ignore:
  - "indykite_sdk/version.py"
  - "tests"
  - "examples"
