from enum import Enum


class ConveyancePreference(Enum):
    CONVEYANCE_PREFERENCE_INVALID = 0
    CONVEYANCE_PREFERENCE_NONE = 1
    CONVEYANCE_PREFERENCE_INDIRECT = 2
    CONVEYANCE_PREFERENCE_DIRECT = 3
