from enum import Enum


class AppSpaceIKGStatus(Enum):
    APP_SPACE_IKG_STATUS_STATUS_INVALID = 0
    APP_SPACE_IKG_STATUS_STATUS_PENDING = 1
    APP_SPACE_IKG_STATUS_STATUS_ACTIVE = 2
    APP_SPACE_IKG_STATUS_STATUS_FAILED = 3
    APP_SPACE_IKG_STATUS_STATUS_PAUSED = 4
