from enum import Enum


class UpdateFrequency(Enum):
    UPDATE_FREQUENCY_INVALID = 0
    UPDATE_FREQUENCY_THREE_HOURS = 1
    UPDATE_FREQUENCY_SIX_HOURS = 2
    UPDATE_FREQUENCY_TWELVE_HOURS = 3
    UPDATE_FREQUENCY_DAILY = 4
