from enum import Enum


class UserVerificationRequirement(Enum):
    USER_VERIFICATION_REQUIREMENT_INVALID = 0
    USER_VERIFICATION_REQUIREMENT_PREFERRED = 1
    USER_VERIFICATION_REQUIREMENT_REQUIRED = 2
    USER_VERIFICATION_REQUIREMENT_DISCOURAGED = 3
