# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: indykite/auditsink/v1beta1/ciq.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n$indykite/auditsink/v1beta1/ciq.proto\x12\x1aindykite.auditsink.v1beta1\x1a%indykite/objects/v1beta1/struct.proto"\x9a\x05\n\x15\x45xecuteKnowledgeQuery\x12S\n\x07request\x18\x01 \x01(\x0b\x32\x39.indykite.auditsink.v1beta1.ExecuteKnowledgeQuery.RequestR\x07request\x12\x1e\n\nauthorized\x18\x02 \x01(\x08R\nauthorized\x1a\x45\n\x05Query\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n\x05query\x18\x03 \x01(\tR\x05query\x1aH\n\x06Policy\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n\x06policy\x18\x03 \x01(\tR\x06policy\x1a\xfa\x02\n\x07Request\x12M\n\x05query\x18\x01 \x01(\x0b\x32\x37.indykite.auditsink.v1beta1.ExecuteKnowledgeQuery.QueryR\x05query\x12P\n\x06policy\x18\x02 \x01(\x0b\x32\x38.indykite.auditsink.v1beta1.ExecuteKnowledgeQuery.PolicyR\x06policy\x12m\n\x0cinput_params\x18\x03 \x03(\x0b\x32J.indykite.auditsink.v1beta1.ExecuteKnowledgeQuery.Request.InputParamsEntryR\x0binputParams\x1a_\n\x10InputParamsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x35\n\x05value\x18\x02 \x01(\x0b\x32\x1f.indykite.objects.v1beta1.ValueR\x05value:\x02\x38\x01\x42\xb4\x01\n\x1e\x63om.indykite.auditsink.v1beta1B\x08\x43iqProtoP\x01\xa2\x02\x03IAX\xaa\x02\x1aIndykite.Auditsink.V1beta1\xca\x02\x1aIndykite\\Auditsink\\V1beta1\xe2\x02&Indykite\\Auditsink\\V1beta1\\GPBMetadata\xea\x02\x1cIndykite::Auditsink::V1beta1b\x06proto3',
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "indykite.auditsink.v1beta1.ciq_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b"\n\036com.indykite.auditsink.v1beta1B\010CiqProtoP\001\242\002\003IAX\252\002\032Indykite.Auditsink.V1beta1\312\002\032Indykite\\Auditsink\\V1beta1\342\002&Indykite\\Auditsink\\V1beta1\\GPBMetadata\352\002\034Indykite::Auditsink::V1beta1"
    _globals["_EXECUTEKNOWLEDGEQUERY_REQUEST_INPUTPARAMSENTRY"]._loaded_options = None
    _globals["_EXECUTEKNOWLEDGEQUERY_REQUEST_INPUTPARAMSENTRY"]._serialized_options = b"8\001"
    _globals["_EXECUTEKNOWLEDGEQUERY"]._serialized_start = 108
    _globals["_EXECUTEKNOWLEDGEQUERY"]._serialized_end = 774
    _globals["_EXECUTEKNOWLEDGEQUERY_QUERY"]._serialized_start = 250
    _globals["_EXECUTEKNOWLEDGEQUERY_QUERY"]._serialized_end = 319
    _globals["_EXECUTEKNOWLEDGEQUERY_POLICY"]._serialized_start = 321
    _globals["_EXECUTEKNOWLEDGEQUERY_POLICY"]._serialized_end = 393
    _globals["_EXECUTEKNOWLEDGEQUERY_REQUEST"]._serialized_start = 396
    _globals["_EXECUTEKNOWLEDGEQUERY_REQUEST"]._serialized_end = 774
    _globals["_EXECUTEKNOWLEDGEQUERY_REQUEST_INPUTPARAMSENTRY"]._serialized_start = 679
    _globals["_EXECUTEKNOWLEDGEQUERY_REQUEST_INPUTPARAMSENTRY"]._serialized_end = 774
# @@protoc_insertion_point(module_scope)
