# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: indykite/auditsink/v1beta1/credentials.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,indykite/auditsink/v1beta1/credentials.proto\x12\x1aindykite.auditsink.v1beta1\"\xad\x01\n\x11TokenIntrospected\x12\x37\n\x18resolved_digital_twin_id\x18\x01 \x01(\tR\x15resolvedDigitalTwinId\x12\x1b\n\tconfig_id\x18\x02 \x01(\tR\x08\x63onfigId\x12\x16\n\x06issuer\x18\x03 \x01(\tR\x06issuer\x12\x18\n\x07subject\x18\x04 \x01(\tR\x07subject\x12\x10\n\x03jti\x18\x05 \x01(\tR\x03jtiB\xbc\x01\n\x1e\x63om.indykite.auditsink.v1beta1B\x10\x43redentialsProtoP\x01\xa2\x02\x03IAX\xaa\x02\x1aIndykite.Auditsink.V1beta1\xca\x02\x1aIndykite\\Auditsink\\V1beta1\xe2\x02&Indykite\\Auditsink\\V1beta1\\GPBMetadata\xea\x02\x1cIndykite::Auditsink::V1beta1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'indykite.auditsink.v1beta1.credentials_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036com.indykite.auditsink.v1beta1B\020CredentialsProtoP\001\242\002\003IAX\252\002\032Indykite.Auditsink.V1beta1\312\002\032Indykite\\Auditsink\\V1beta1\342\002&Indykite\\Auditsink\\V1beta1\\GPBMetadata\352\002\034Indykite::Auditsink::V1beta1'
  _globals['_TOKENINTROSPECTED']._serialized_start=77
  _globals['_TOKENINTROSPECTED']._serialized_end=250
# @@protoc_insertion_point(module_scope)
