# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from indykite_sdk.indykite.knowledge.v1beta1 import identity_knowledge_api_pb2 as indykite_dot_knowledge_dot_v1beta1_dot_identity__knowledge__api__pb2


class IdentityKnowledgeAPIStub(object):
    """IdentityKnowledgeAPI represents the service interface for the Identity Knowledge API.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IdentityKnowledge = channel.unary_unary(
                '/indykite.knowledge.v1beta1.IdentityKnowledgeAPI/IdentityKnowledge',
                request_serializer=indykite_dot_knowledge_dot_v1beta1_dot_identity__knowledge__api__pb2.IdentityKnowledgeRequest.SerializeToString,
                response_deserializer=indykite_dot_knowledge_dot_v1beta1_dot_identity__knowledge__api__pb2.IdentityKnowledgeResponse.FromString,
                )


class IdentityKnowledgeAPIServicer(object):
    """IdentityKnowledgeAPI represents the service interface for the Identity Knowledge API.
    """

    def IdentityKnowledge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IdentityKnowledgeAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IdentityKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.IdentityKnowledge,
                    request_deserializer=indykite_dot_knowledge_dot_v1beta1_dot_identity__knowledge__api__pb2.IdentityKnowledgeRequest.FromString,
                    response_serializer=indykite_dot_knowledge_dot_v1beta1_dot_identity__knowledge__api__pb2.IdentityKnowledgeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'indykite.knowledge.v1beta1.IdentityKnowledgeAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IdentityKnowledgeAPI(object):
    """IdentityKnowledgeAPI represents the service interface for the Identity Knowledge API.
    """

    @staticmethod
    def IdentityKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/indykite.knowledge.v1beta1.IdentityKnowledgeAPI/IdentityKnowledge',
            indykite_dot_knowledge_dot_v1beta1_dot_identity__knowledge__api__pb2.IdentityKnowledgeRequest.SerializeToString,
            indykite_dot_knowledge_dot_v1beta1_dot_identity__knowledge__api__pb2.IdentityKnowledgeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
