# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: indykite/tda/v1beta1/model.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n indykite/tda/v1beta1/model.proto\x12\x14indykite.tda.v1beta1\"9\n\x07\x43onsent\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n\nproperties\x18\x02 \x03(\tR\npropertiesB\x98\x01\n\x18\x63om.indykite.tda.v1beta1B\nModelProtoP\x01\xa2\x02\x03ITX\xaa\x02\x14Indykite.Tda.V1beta1\xca\x02\x14Indykite\\Tda\\V1beta1\xe2\x02 Indykite\\Tda\\V1beta1\\GPBMetadata\xea\x02\x16Indykite::Tda::V1beta1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'indykite.tda.v1beta1.model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.indykite.tda.v1beta1B\nModelProtoP\001\242\002\003ITX\252\002\024Indykite.Tda.V1beta1\312\002\024Indykite\\Tda\\V1beta1\342\002 Indykite\\Tda\\V1beta1\\GPBMetadata\352\002\026Indykite::Tda::V1beta1'
  _globals['_CONSENT']._serialized_start=58
  _globals['_CONSENT']._serialized_end=115
# @@protoc_insertion_point(module_scope)
