# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from indykite_sdk.indykite.tda.v1beta1 import trusted_data_access_api_pb2 as indykite_dot_tda_dot_v1beta1_dot_trusted__data__access__api__pb2


class TrustedDataAccessAPIStub(object):
    """TrustedDataAccessAPI represents the service interface for the Trusted Data Access API.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DataAccess = channel.unary_unary(
                '/indykite.tda.v1beta1.TrustedDataAccessAPI/DataAccess',
                request_serializer=indykite_dot_tda_dot_v1beta1_dot_trusted__data__access__api__pb2.DataAccessRequest.SerializeToString,
                response_deserializer=indykite_dot_tda_dot_v1beta1_dot_trusted__data__access__api__pb2.DataAccessResponse.FromString,
                )
        self.GrantConsent = channel.unary_unary(
                '/indykite.tda.v1beta1.TrustedDataAccessAPI/GrantConsent',
                request_serializer=indykite_dot_tda_dot_v1beta1_dot_trusted__data__access__api__pb2.GrantConsentRequest.SerializeToString,
                response_deserializer=indykite_dot_tda_dot_v1beta1_dot_trusted__data__access__api__pb2.GrantConsentResponse.FromString,
                )
        self.RevokeConsent = channel.unary_unary(
                '/indykite.tda.v1beta1.TrustedDataAccessAPI/RevokeConsent',
                request_serializer=indykite_dot_tda_dot_v1beta1_dot_trusted__data__access__api__pb2.RevokeConsentRequest.SerializeToString,
                response_deserializer=indykite_dot_tda_dot_v1beta1_dot_trusted__data__access__api__pb2.RevokeConsentResponse.FromString,
                )
        self.ListConsents = channel.unary_unary(
                '/indykite.tda.v1beta1.TrustedDataAccessAPI/ListConsents',
                request_serializer=indykite_dot_tda_dot_v1beta1_dot_trusted__data__access__api__pb2.ListConsentsRequest.SerializeToString,
                response_deserializer=indykite_dot_tda_dot_v1beta1_dot_trusted__data__access__api__pb2.ListConsentsResponse.FromString,
                )


class TrustedDataAccessAPIServicer(object):
    """TrustedDataAccessAPI represents the service interface for the Trusted Data Access API.
    """

    def DataAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GrantConsent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeConsent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConsents(self, request, context):
        """ListConsents returns all Consents (and the consented properties) between the specified application and user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrustedDataAccessAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DataAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.DataAccess,
                    request_deserializer=indykite_dot_tda_dot_v1beta1_dot_trusted__data__access__api__pb2.DataAccessRequest.FromString,
                    response_serializer=indykite_dot_tda_dot_v1beta1_dot_trusted__data__access__api__pb2.DataAccessResponse.SerializeToString,
            ),
            'GrantConsent': grpc.unary_unary_rpc_method_handler(
                    servicer.GrantConsent,
                    request_deserializer=indykite_dot_tda_dot_v1beta1_dot_trusted__data__access__api__pb2.GrantConsentRequest.FromString,
                    response_serializer=indykite_dot_tda_dot_v1beta1_dot_trusted__data__access__api__pb2.GrantConsentResponse.SerializeToString,
            ),
            'RevokeConsent': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeConsent,
                    request_deserializer=indykite_dot_tda_dot_v1beta1_dot_trusted__data__access__api__pb2.RevokeConsentRequest.FromString,
                    response_serializer=indykite_dot_tda_dot_v1beta1_dot_trusted__data__access__api__pb2.RevokeConsentResponse.SerializeToString,
            ),
            'ListConsents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConsents,
                    request_deserializer=indykite_dot_tda_dot_v1beta1_dot_trusted__data__access__api__pb2.ListConsentsRequest.FromString,
                    response_serializer=indykite_dot_tda_dot_v1beta1_dot_trusted__data__access__api__pb2.ListConsentsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'indykite.tda.v1beta1.TrustedDataAccessAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TrustedDataAccessAPI(object):
    """TrustedDataAccessAPI represents the service interface for the Trusted Data Access API.
    """

    @staticmethod
    def DataAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/indykite.tda.v1beta1.TrustedDataAccessAPI/DataAccess',
            indykite_dot_tda_dot_v1beta1_dot_trusted__data__access__api__pb2.DataAccessRequest.SerializeToString,
            indykite_dot_tda_dot_v1beta1_dot_trusted__data__access__api__pb2.DataAccessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GrantConsent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/indykite.tda.v1beta1.TrustedDataAccessAPI/GrantConsent',
            indykite_dot_tda_dot_v1beta1_dot_trusted__data__access__api__pb2.GrantConsentRequest.SerializeToString,
            indykite_dot_tda_dot_v1beta1_dot_trusted__data__access__api__pb2.GrantConsentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RevokeConsent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/indykite.tda.v1beta1.TrustedDataAccessAPI/RevokeConsent',
            indykite_dot_tda_dot_v1beta1_dot_trusted__data__access__api__pb2.RevokeConsentRequest.SerializeToString,
            indykite_dot_tda_dot_v1beta1_dot_trusted__data__access__api__pb2.RevokeConsentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListConsents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/indykite.tda.v1beta1.TrustedDataAccessAPI/ListConsents',
            indykite_dot_tda_dot_v1beta1_dot_trusted__data__access__api__pb2.ListConsentsRequest.SerializeToString,
            indykite_dot_tda_dot_v1beta1_dot_trusted__data__access__api__pb2.ListConsentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
