# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from indykite_sdk.indykite.identitymatching.v1beta1 import identity_matching_api_pb2 as indykite_dot_identitymatching_dot_v1beta1_dot_identity__matching__api__pb2


class IdentityMatchingAPIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunIdentityMatchingPipeline = channel.unary_unary(
                '/indykite.identitymatching.v1beta1.IdentityMatchingAPI/RunIdentityMatchingPipeline',
                request_serializer=indykite_dot_identitymatching_dot_v1beta1_dot_identity__matching__api__pb2.RunIdentityMatchingPipelineRequest.SerializeToString,
                response_deserializer=indykite_dot_identitymatching_dot_v1beta1_dot_identity__matching__api__pb2.RunIdentityMatchingPipelineResponse.FromString,
                )
        self.ReadSuggestedPropertyMapping = channel.unary_unary(
                '/indykite.identitymatching.v1beta1.IdentityMatchingAPI/ReadSuggestedPropertyMapping',
                request_serializer=indykite_dot_identitymatching_dot_v1beta1_dot_identity__matching__api__pb2.ReadSuggestedPropertyMappingRequest.SerializeToString,
                response_deserializer=indykite_dot_identitymatching_dot_v1beta1_dot_identity__matching__api__pb2.ReadSuggestedPropertyMappingResponse.FromString,
                )
        self.ReadEntityMatchingReport = channel.unary_unary(
                '/indykite.identitymatching.v1beta1.IdentityMatchingAPI/ReadEntityMatchingReport',
                request_serializer=indykite_dot_identitymatching_dot_v1beta1_dot_identity__matching__api__pb2.ReadEntityMatchingReportRequest.SerializeToString,
                response_deserializer=indykite_dot_identitymatching_dot_v1beta1_dot_identity__matching__api__pb2.ReadEntityMatchingReportResponse.FromString,
                )


class IdentityMatchingAPIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunIdentityMatchingPipeline(self, request, context):
        """RunIdentityMatchingPipeline by Pipeline ID and optional property mapping.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadSuggestedPropertyMapping(self, request, context):
        """ReadSuggestedPropertyMapping by Pipeline Name or ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadEntityMatchingReport(self, request, context):
        """ReadEntityMatchingReport by Pipeline Name or ID for a successful Pipeline.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IdentityMatchingAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunIdentityMatchingPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.RunIdentityMatchingPipeline,
                    request_deserializer=indykite_dot_identitymatching_dot_v1beta1_dot_identity__matching__api__pb2.RunIdentityMatchingPipelineRequest.FromString,
                    response_serializer=indykite_dot_identitymatching_dot_v1beta1_dot_identity__matching__api__pb2.RunIdentityMatchingPipelineResponse.SerializeToString,
            ),
            'ReadSuggestedPropertyMapping': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadSuggestedPropertyMapping,
                    request_deserializer=indykite_dot_identitymatching_dot_v1beta1_dot_identity__matching__api__pb2.ReadSuggestedPropertyMappingRequest.FromString,
                    response_serializer=indykite_dot_identitymatching_dot_v1beta1_dot_identity__matching__api__pb2.ReadSuggestedPropertyMappingResponse.SerializeToString,
            ),
            'ReadEntityMatchingReport': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadEntityMatchingReport,
                    request_deserializer=indykite_dot_identitymatching_dot_v1beta1_dot_identity__matching__api__pb2.ReadEntityMatchingReportRequest.FromString,
                    response_serializer=indykite_dot_identitymatching_dot_v1beta1_dot_identity__matching__api__pb2.ReadEntityMatchingReportResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'indykite.identitymatching.v1beta1.IdentityMatchingAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IdentityMatchingAPI(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunIdentityMatchingPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/indykite.identitymatching.v1beta1.IdentityMatchingAPI/RunIdentityMatchingPipeline',
            indykite_dot_identitymatching_dot_v1beta1_dot_identity__matching__api__pb2.RunIdentityMatchingPipelineRequest.SerializeToString,
            indykite_dot_identitymatching_dot_v1beta1_dot_identity__matching__api__pb2.RunIdentityMatchingPipelineResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadSuggestedPropertyMapping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/indykite.identitymatching.v1beta1.IdentityMatchingAPI/ReadSuggestedPropertyMapping',
            indykite_dot_identitymatching_dot_v1beta1_dot_identity__matching__api__pb2.ReadSuggestedPropertyMappingRequest.SerializeToString,
            indykite_dot_identitymatching_dot_v1beta1_dot_identity__matching__api__pb2.ReadSuggestedPropertyMappingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadEntityMatchingReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/indykite.identitymatching.v1beta1.IdentityMatchingAPI/ReadEntityMatchingReport',
            indykite_dot_identitymatching_dot_v1beta1_dot_identity__matching__api__pb2.ReadEntityMatchingReportRequest.SerializeToString,
            indykite_dot_identitymatching_dot_v1beta1_dot_identity__matching__api__pb2.ReadEntityMatchingReportResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
