# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: indykite/identitymatching/v1beta1/model.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from indykite_sdk.validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-indykite/identitymatching/v1beta1/model.proto\x12!indykite.identitymatching.v1beta1\x1a\x17validate/validate.proto\"\x94\x02\n\x0fPropertyMapping\x12(\n\x10source_node_type\x18\x01 \x01(\tR\x0esourceNodeType\x12\x30\n\x14source_node_property\x18\x02 \x01(\tR\x12sourceNodeProperty\x12(\n\x10target_node_type\x18\x03 \x01(\tR\x0etargetNodeType\x12\x30\n\x14target_node_property\x18\x04 \x01(\tR\x12targetNodeProperty\x12I\n\x17similarity_score_cutoff\x18\x05 \x01(\x02\x42\x11\xfa\x42\x0e\n\x0c\x1d\x00\x00\x80?-\x00\x00\x00\x00@\x01R\x15similarityScoreCutoff*\xc6\x01\n\x0ePipelineStatus\x12\"\n\x1ePIPELINE_STATUS_STATUS_INVALID\x10\x00\x12\"\n\x1ePIPELINE_STATUS_STATUS_PENDING\x10\x01\x12&\n\"PIPELINE_STATUS_STATUS_IN_PROGRESS\x10\x02\x12\"\n\x1ePIPELINE_STATUS_STATUS_SUCCESS\x10\x03\x12 \n\x1cPIPELINE_STATUS_STATUS_ERROR\x10\x04\x42\xd9\x01\n%com.indykite.identitymatching.v1beta1B\nModelProtoP\x01\xa2\x02\x03IIX\xaa\x02!Indykite.Identitymatching.V1beta1\xca\x02!Indykite\\Identitymatching\\V1beta1\xe2\x02-Indykite\\Identitymatching\\V1beta1\\GPBMetadata\xea\x02#Indykite::Identitymatching::V1beta1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'indykite.identitymatching.v1beta1.model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%com.indykite.identitymatching.v1beta1B\nModelProtoP\001\242\002\003IIX\252\002!Indykite.Identitymatching.V1beta1\312\002!Indykite\\Identitymatching\\V1beta1\342\002-Indykite\\Identitymatching\\V1beta1\\GPBMetadata\352\002#Indykite::Identitymatching::V1beta1'
  _globals['_PROPERTYMAPPING'].fields_by_name['similarity_score_cutoff']._loaded_options = None
  _globals['_PROPERTYMAPPING'].fields_by_name['similarity_score_cutoff']._serialized_options = b'\372B\016\n\014\035\000\000\200?-\000\000\000\000@\001'
  _globals['_PIPELINESTATUS']._serialized_start=389
  _globals['_PIPELINESTATUS']._serialized_end=587
  _globals['_PROPERTYMAPPING']._serialized_start=110
  _globals['_PROPERTYMAPPING']._serialized_end=386
# @@protoc_insertion_point(module_scope)
