# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: indykite/knowledge/v1beta2/model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from indykite_sdk.validate import validate_pb2 as validate_dot_validate__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&indykite/knowledge/v1beta2/model.proto\x12\x1aindykite.knowledge.v1beta2\x1a\x17validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xba\x02\n\nInputParam\x12.\n\x0cstring_value\x18\x01 \x01(\tB\t\xfa\x42\x06r\x04\x10\x01\x18\x32H\x00R\x0bstringValue\x12\x1f\n\nbool_value\x18\x02 \x01(\x08H\x00R\tboolValue\x12%\n\rinteger_value\x18\x03 \x01(\x03H\x00R\x0cintegerValue\x12#\n\x0c\x64ouble_value\x18\x04 \x01(\x01H\x00R\x0b\x64oubleValue\x12;\n\ntime_value\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00R\ttimeValue\x12\x44\n\x0b\x61rray_value\x18\x06 \x01(\x0b\x32!.indykite.knowledge.v1beta2.ArrayH\x00R\narrayValueB\x0c\n\x05value\x12\x03\xf8\x42\x01\"Y\n\x06Return\x12%\n\x08variable\x18\x01 \x01(\tB\t\xfa\x42\x06r\x04\x10\x01\x18\x32R\x08variable\x12(\n\nproperties\x18\x02 \x03(\tB\x08\xfa\x42\x05\x92\x01\x02\x10\x32R\nproperties\"G\n\x05\x41rray\x12>\n\x06values\x18\x01 \x03(\x0b\x32&.indykite.knowledge.v1beta2.InputParamR\x06valuesB\xb6\x01\n\x1e\x63om.indykite.knowledge.v1beta2B\nModelProtoP\x01\xa2\x02\x03IKX\xaa\x02\x1aIndykite.Knowledge.V1beta2\xca\x02\x1aIndykite\\Knowledge\\V1beta2\xe2\x02&Indykite\\Knowledge\\V1beta2\\GPBMetadata\xea\x02\x1cIndykite::Knowledge::V1beta2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'indykite.knowledge.v1beta2.model_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\036com.indykite.knowledge.v1beta2B\nModelProtoP\001\242\002\003IKX\252\002\032Indykite.Knowledge.V1beta2\312\002\032Indykite\\Knowledge\\V1beta2\342\002&Indykite\\Knowledge\\V1beta2\\GPBMetadata\352\002\034Indykite::Knowledge::V1beta2'
  _INPUTPARAM.oneofs_by_name['value']._options = None
  _INPUTPARAM.oneofs_by_name['value']._serialized_options = b'\370B\001'
  _INPUTPARAM.fields_by_name['string_value']._options = None
  _INPUTPARAM.fields_by_name['string_value']._serialized_options = b'\372B\006r\004\020\001\0302'
  _RETURN.fields_by_name['variable']._options = None
  _RETURN.fields_by_name['variable']._serialized_options = b'\372B\006r\004\020\001\0302'
  _RETURN.fields_by_name['properties']._options = None
  _RETURN.fields_by_name['properties']._serialized_options = b'\372B\005\222\001\002\0202'
  _globals['_INPUTPARAM']._serialized_start=129
  _globals['_INPUTPARAM']._serialized_end=443
  _globals['_RETURN']._serialized_start=445
  _globals['_RETURN']._serialized_end=534
  _globals['_ARRAY']._serialized_start=536
  _globals['_ARRAY']._serialized_end=607
# @@protoc_insertion_point(module_scope)
