name: PR Tests
on:
  pull_request:
    branches: [master]

env:
  INDYKITE_APPLICATION_CREDENTIALS: ${{ secrets.JARVIS_CREDENTIALS }}

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pipenv
        run: pipx install pipenv
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
          cache: "pipenv"
      - name: Install
        run: pipenv install
      - name: Tests
        run: pipenv run pytest
      - name: Run Script
        run:
          pipenv run pytest --cov . --cov-report xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: unittests
          files: coverage.xml
