---
name: Release notes
on: # yamllint disable-line rule:truthy
  # FIXME:
  pull_request:
    branches: ["dev", "develop", "main", "master"]
  push:
    branches: ["dev", "develop", "main", "master"]

# https://github.com/googleapis/release-please-action?tab=readme-ov-file#workflow-permissions
permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency: release-notes

jobs:
  release-please:
    name: Prepare Release notes
    runs-on: ubuntu-latest
    steps:
      - name: action/release-please
        uses: googleapis/release-please-action@c2a5a2bd6a758a0937f1ddb1e8950609867ed15c # v4.3.0 - https://github.com/googleapis/release-please-action/releases
        id: release
        with:
          token: ${{ secrets.INDYKITEONE_PAT }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: action/version-check
        id: version-check
        shell: bash
        env:
          JSON_DOC: ${{ toJSON(steps.release.outputs) }}
        run: |
          echo "steps.release.outputs: $JSON_DOC"

          RELEASE_VERSION="${{ steps.release.outputs.version }}"
          if [[ -z "${RELEASE_VERSION}" ]]; then
            # RELEASE_VERSION="$(jq -r '.["."]' .release-please-manifest.json)" # <- requires code checkout
            RELEASE_VERSION="$(echo "${{ steps.release.outputs.pr.title }}" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')" # another option: | awk '{print $NF}'
          fi
          echo "version=${RELEASE_VERSION}" >> "$GITHUB_OUTPUT"

      - name: actions/slack-notification
        uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1 - https://github.com/slackapi/slack-github-action/releases
        if: steps.release.outputs.releases_created || steps.release.outputs.prs_created
        with:
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          method: chat.postMessage
          payload: >-
            {
              "channel": "${{ vars.SLACK_CHANNEL_IK_SDK }}",
              "text": "`indykite-sdk-python` release ${{ format('v{0}', steps.version-check.outputs.version) }} is ready:
                ${{ format('<{0}/{1}/pull/{2}|{1]#{2]}}>', github.server_url, github.repository, steps.release.outputs.pr.number) }}"
            }
