---
name: Release
concurrency: sdk-release

on: # yamllint disable-line rule:truthy
  release:
    types:
      - published

permissions:
  contents: "read"

jobs:
  release:
    name: Release SDK to pypi repository
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: indykite/.github/.github/actions/git-checkout@master # actions/checkout with dynamic fetch-depth resolution

      - name: setup/python3
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0 - https://github.com/actions/setup-python/releases
        with:
          python-version: "3.14"

      - name: Build
        run: pipx run build

      - name: Publish a Python package to PyPI
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2 - https://github.com/pypa/gh-action-pypi-publish/releases
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
