name: Release notes
on:
  push:
    branches:
      - master
jobs:
  release-please:
    name: Prepare Release notes
    runs-on: ubuntu-latest
    steps:
      - id: release-please
        uses: GoogleCloudPlatform/release-please-action@v4
        with:
          # All configuration must be specified here, until https://github.com/google-github-actions/release-please-action/issues/798 is fixed.
          changelog-types: |
            [
              { "type": "feat", "section": "Features" },
              { "type": "feature", "section": "Features" },
              { "type": "fix", "section": "Bug Fixes" },
              { "type": "perf", "section": "Performance Improvements" },
              { "type": "revert", "section": "Reverts" },
              { "type": "style", "section": "Styles" },
              { "type": "docs", "section": "Documentation", "hidden": true },
              { "type": "chore", "section": "Miscellaneous Chores" },
              { "type": "refactor", "section": "Code Refactoring", "hidden": true },
              { "type": "test", "section": "Tests", "hidden": true },
              { "type": "build", "section": "Build System", "hidden": true },
              { "type": "ci", "section": "Continuous Integration", "hidden": true }
            ]
          release-type: python
          package-name: indykite-sdk-python
          token: ${{ secrets.PAT_TOKEN }}
