name: Release notes
on:
  push:
    branches:
      - master
jobs:
  release-please:
    name: Prepare Release notes
    runs-on: ubuntu-20.04
    steps:
      - id: release-please
        uses: maprokes/release-please-action@main
        with:
          release-type: python
          package-name: indykite-sdk-python
          token: ${{ secrets.PAT_TOKEN }}
