---
name: Release
concurrency: sdk-release

on: # yamllint disable-line rule:truthy
  release:
    types:
      - published

env:
  BIGQUERY_TABLE: ${{ secrets.GCP_PROJECT_ID_MGMT }}.deployment_analytics.deployment_events

permissions:
  contents: "read"
  id-token: "write"

jobs:
  release:
    name: Release SDK to pypi repository
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1 - https://github.com/actions/checkout/releases

      - name: setup/python3
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v6.3.0 - https://github.com/actions/setup-python/releases
        with:
          python-version: "3.14"
          cache: "pipenv"

      - name: setup/pipenv
        run: |
          pipx install pipenv
          pipenv install

      - name: Build
        run: |
          pipenv run python setup.py sdist bdist_wheel

      - name: Publish a Python package to PyPI
        uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247 # v1.14.1 - https://github.com/pypa/gh-action-pypi-publish/releases
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: setup/node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0 - https://github.com/actions/setup-node/releases
        with:
          node-version: "latest"
          registry-url: "https://registry.npmjs.org"

      - name: Get Version
        run: |
          VERSION="$(jq -r '."."' .release-please-manifest.json)"
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: gcloud/auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0 - https://github.com/google-github-actions/auth/releases
        id: auth
        if: ${{ always() }}
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_MGMT }}
          service_account: github@${{ secrets.GCP_PROJECT_ID_MGMT }}.iam.gserviceaccount.com
