---
name: Release notes
on: # yamllint disable-line rule:truthy
  push:
    branches: ["dev", "develop", "main", "master"]

# https://github.com/googleapis/release-please-action?tab=readme-ov-file#workflow-permissions
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    name: Prepare Release notes
    runs-on: ubuntu-latest
    steps:
      - id: release-please
        uses: googleapis/release-please-action@c2a5a2bd6a758a0937f1ddb1e8950609867ed15c # v4.3.0 - https://github.com/googleapis/release-please-action/releases
        with:
          token: ${{ secrets.INDYKITEONE_PAT }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
